### ISSUE TITLE
(HTTP code 404) no such image - No such image: mongo:latest

### ISSUE THREAD

**Issue by moussa86** [balena-io/balena-cli#1090]
Trying to build a docker for RocketChat. when the docker-compose tries to get Mongo image an Http 404 error no such image found
[docker-compose.yml.txt](https://github.com/balena-io/balena-cli/files/2825653/docker-compose.yml.txt)

[Info]    Starting build on device 192.168.100.141
[Info]    Compose file detected
(HTTP code 404) no such image - No such image: mongo:latest

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io

**Comment by Santiago-vdk** [comment]
Same here.

```
[Info]    Starting build on device 192.168.0.103
[Info]    Compose file detected
(HTTP code 404) no such image - No such image: mongo:latest 

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io
```
Docker-compose.yml
```
version: '2'
services:

  postgres:                                                                                     
    container_name: postgres                                                                    
    image: arm32v7/postgres:9                                                                   
    volumes:                                                                                    
      - 'postgres-data:/var/lib/postgresql/data'                                        
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:                                                                                    
      - 'mongo-data:/data/db' 

  mongo-express:
    image: arm64v8/mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes: 
  postgres-data:
  mongo-data:
```

Already tried  arm64v8/mongo.
arm64v8/mongo-express returns success

```
host:          b9a8d03.local
  address:       xxx.xxx.xxx.xxx
  dockerInfo: 
    Containers:        5
    ContainersRunning: 5
    ContainersPaused:  0
    ContainersStopped: 0
    Images:            34
    Driver:            aufs
    SystemTime:        2019-05-03T03:47:48.491798087Z
    KernelVersion:     4.14.98
    OperatingSystem:   balenaOS 2.31.5+rev1
    Architecture:      armv7l
  dockerVersion: 
    Version:    17.12.0-dev
    ApiVersion: 1.35
```
