### ISSUE TITLE
balena push selects incorrect image (multiarch images, Docker manifest)

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1408]
[As reported in the forums](https://forums.balena.io/t/use-pre-build-multiarch-image-from-docker-hub/26110) (with thanks!), running `balena push` with a multiarch image hosted in Docker Hub, with a docker-compose file such as the following, results in "exec format error":

```
services:
  lora-connect:
    image: arribada/lora-connect
    ports:
    - "8070:8070"
```

The problem may not actually be in balena-cli, but rather the cloud builders, but this issue is being created to give more visibility to the issue and keep track of its resolution.

**Comment by pdcastro** [comment]
Link to a related issue in a private GitHub repo (access to balena users only):
https://github.com/balena-io/resin-builder/issues/626

**Comment by krasi-georgiev** [comment]
@pdcastro sorry for the noise, but this is a blocker for a project that is suppose to go in production soon so wondering if there has been any development towards fixing this bug. Some update would be greatly appreciated.

**Comment by pdcastro** [comment]
@krasi-georgiev, I'm afraid there hasn't been activity on this issue as far as I am aware. If helpful, note that balena supports Dockerfile templates to allow a single Dockerfile to pull from base images of different architectures:
https://www.balena.io/docs/learn/develop/dockerfile/#dockerfile-templates

That's how `balena push` has "traditionally" dealt with multiple architectures. I understand that multiarch image support based on manifest files is a relatively new feature introduced by Docker. We intend to add support for it, but at the moment I don't have an ETA to share.

**Comment by krasi-georgiev** [comment]
Thanks. 

> That's how balena push has "traditionally" dealt with multiple architectures.

I might be wrong, but I think this feature has been in docker since one of the early versions so it is not new. Until recently though it wasn't very easy to push multi arch images and this changed with one of the recent versions which simplifies that process.

**Comment by MatthewCroughan** [comment]
https://github.com/balena-io/balena-cli/issues/1508

**Comment by krasi-georgiev** [comment]
it would be useful to get some automated updates from the internal discussions and decisions as well

**Comment by krasi-georgiev** [comment]
Has there been any progress with this.

I just tried it again with 12.20.0 and I still get 

```
.
.
[Success]          Successfully uploaded images
[Error]            Some services failed to build:
[Error]              Service: lora-gps-server
[Error]                Error: no matching manifest for unknown in the manifest list entries
[Info]             Built on arm01
[Error]            Not deploying release.
```

The docker image does have a manifest for arm.

**Comment by krasi-georgiev** [comment]
I just tried 12.33.0 and seems to be ok so can close it, will reopen it if still facing issues.

**Comment by pdcastro** [comment]
I think livepush / push to local device (`balena push <ip-address>`) still doesn't work with multiarch images, but push to cloud (`balena push myApp`) works.

**Comment by krasi-georgiev** [comment]
noted, I was using push to cloud

**Comment by maggie0002** [comment]
> I think livepush / push to local device (`balena push <ip-address>`) still doesn't work with multiarch images, but push to cloud (`balena push myApp`) works.

How about ‘deploy’ for openBalena? If I specify an image from Docker Hub, e.g. linuxserver/bookstack, will it pull the image for the arch it is intending to deploy to (arm 7) or pull for my local env (amd64)?

**Comment by compiaffe** [comment]
`balena deploy` using a multiarch still does not work. 
i.e. docker-compose.yml as i.e.:

```
version: '2.1'
volumes:
  workdir:
services:
  gha-runner:
    image: myoung34/github-runner:latest
    environment:
      - RUNNER_NAME_PREFIX=nano
      - RUNNER_WORKDIR=/tmp/workdir
      - ORG_RUNNER=true
      - ORG_NAME=our_org
      - LABELS=linux-armv8-l4t-t210
    devices:
      - '/dev:/dev'
      - '/sys:/sys'
    privileged: true
    restart: "unless-stopped"
    volumes:
      - workdir:/tmp/workdir:rw

    # command: ["tail","-f", "/dev/null"] # for debugging
    labels:
      io.balena.features.balena-socket: '1'
```

still causes a `exec error`.

The target is a Jetson Nano
