### ISSUE TITLE
depends_on should trigger service re-creation when the service it depends on has changed

### ISSUE THREAD

**Issue by krasi-georgiev** [balena-io/balena-cli#1447]
`alertmanager` depends on `env-config` but when I change an env variable in `env-config` only `env-config` gets recreated. 

The use case is that the `alertmanager` doesn't accept env variables as a config so I developped the `env-config` which converts all env variables to files and than I simply use the `/configs/ALERTMANAGER_CONFIG` for the alertmanager configs.

The problem is that when I change the `ALERTMANAGER_CONFIG` only `env-config` gets recreated and the a `alertmanager` never picks up the changes.

11.11.2
from linux zip install

```
version: "2.1"

services:
  env-config:
    image: arribada/env-config
    volumes:
    - configs:/configs/
    command:
        - --dir=/configs/
    environment:
      ALERTMANAGER_CONFIG: |-
        route:
          receiver: 'krasi'
          routes:
          - match:
                alertname: GPSPerimeterBreach
          - match:
                alertname: GPSNoUpdate
        receivers:
        - name: 'krasi'
          pagerduty_configs:
          - routing_key: $ROUTING_KEY
	alertmanager:
	    image: prom/alertmanager
	    depends_on:
	      - env-config
	    volumes:
	    - configs:/configs/
	    ports:
	      - 9093:9093
	    command:
	      - --config.file=/configs/ALERTMANAGER_CONFIG
volumes:
  configs:
```
