### ISSUE TITLE
Can not find custom dockerfile with compose files

### ISSUE THREAD

**Issue by mwohlert** [balena-io/balena-cli#1618]
- **balena CLI version:** 11.25.18
- **Operating system version:** Arch Linux
- **32/64 bit OS and processor:** 64bit
- **Install method:** npm
- **If npm install, Node.js and npm version:** Node v12.6.0 and npm v6.9.0
---

When using docker-compose.yml specifying custom Dockerfile names does not work and will result in the message `Could not find a Dockerfile for this service`.

Example:
```
version: '2.1'
services:
  hello:
    container_name: hello
    build:
      context: ../hello
      dockerfile: Dockerfile.debug
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.balena.update.strategy: kill-then-download
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
    environment:
      - ENV=production
```

**Comment by pdcastro** [comment]
@mwohlert, I was running some tests and I appear to have got successful results by modifying the way that the context path is specified, for example in the following two versions:
```yaml
  hello:
    container_name: hello
    build:
      context: "./hello"
      dockerfile: "Dockerfile.debug"
```
```yaml
  hello:
    container_name: hello
    build:
      context: "."
      dockerfile: "hello/Dockerfile.debug"
```

Could you try if any of the above works for you? I believe that the context path is relative to the location of the `docker-compose.yml` file (i.e., the project root), and it cannot point to a parent folder of the project root, because parent folders are not included in the tar stream that is sent to the Docker daemon or balenaCloud.

Note for future / further investigation: in my tests with `context: "../hello"`, the error message was:
`"Specified file not found or is invalid: Dockerfile.debug"`
instead of: `"Could not find a Dockerfile for this service"`
The two error messages are defined side by side at:
https://github.com/balena-io-modules/resin-bundle-resolve/blob/v4.1.3/src/index.ts#L175-L176
