### ISSUE TITLE
Add validation for docker-compose 'context' folder

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1620]
In the same vein as issues #1421 and #1619 (PR #1571), and motivated by issue #1618, add validation for the `context` fields of a `docker-compose.yml` file: it should not point to a parent/ancestor folder of the project source/root folder, as such folders are not included in the tar stream that gets sent to balenaCloud or the Docker daemon.

Example of invalid context directory:
```
version: '2.1'
services:
  hello:
    container_name: hello
    build:
      context: "../hello"
 ```
Valid values would be for example `"."` or `"./hello"` or `"hello"` (backslashes should probably be allowed on Windows).
