### ISSUE TITLE
Build emulation does not work on non standard Dockerfile names in compose files

### ISSUE THREAD

**Issue by mwohlert** [balena-io/balena-cli#1707]
- **balena CLI version:** 11.30.12
- **Operating system version:**  Arch Linux
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** v12.6.0 and v6.9.0

---

The build emulation now works for dockerfiles, however if this is referenced in a Dockerfile build emulation will not be used.

Dockerfile.debug:
```
FROM balenalib/armv7hf-debian:latest
RUN echo 'hello world'
```

docker-compose.yml:
```
version: '2.1'
services:
  hello:
    container_name: hello
    build:
      context: .
      dockerfile: Dockerfile.debug
```

**Comment by mwohlert** [comment]
Related to #1624

**Comment by jimsynz** [comment]
As per the above linked support thread; this bug also affects users which set the build's `dockerfile` value to anything at all.

For example, the following `docker-compose.yml` fails:

```yml
version: "2"

services:
  with_template:
    build:
      context: .
      dockerfile: ./services/with_template/Dockerfile.template

  without_template:
    build:
      context: .
      dockerfile: ./services/without_template/Dockerfile
```

```
Info]    Building for aarch64/raspberrypi4-64
[Build]   Building services...
[Build]   with_template    Preparing...
[Build]   without_template Preparing...
[Info]    Emulation is enabled
[Build]   with_template    Step 1/3 : FROM balenalib/raspberrypi4-64-debian:latest
[Build]   with_template     ---> 772fa2eae48a
[Build]   with_template    Step 2/3 : RUN "Dockerfile.template" > /wat
[Build]   with_template     ---> Running in 3163eafeb5e8
[Build]   with_template    standard_init_linux.go:211: exec user process caused "exec format error"
[Build]   without_template Step 1/3 : FROM balenalib/rpi-debian:latest
[Build]   without_template  ---> 4b18c0dfa46b
[Build]   without_template Step 2/3 : RUN echo "Dockerfile" > /tmp/wat
[Build]   without_template  ---> Running in 3300b50680cb
[Build]   without_template standard_init_linux.go:211: exec user process caused "exec format error"
[Build]   Built 2 services in 0:21
[Error]   Build failed
The command '/bin/sh -c "Dockerfile.template" > /wat' returned a non-zero code: 1
```
