### ISSUE TITLE
Use of 'build' and 'image' config options together when using compose file prevents containers launching under local push

### ISSUE THREAD

**Issue by beaylott** [balena-io/balena-cli#1874]
In vanilla compose if 'image' and 'build' are used together the effect is to names/tags the built image with the provided image value (see: https://docs.docker.com/compose/compose-file/#build). 

When doing this with balena-cli (11.36.0) and balenaOS (2.47.0+rev1) pushing to a local dev device this seems to prevent the relevant containers from starting properly. 

e.g. something like this will not work:

```
services:
    service1:
        build:
            dockerfile: ./docker/Dockerfile
            context: ./service1
        image: myorg/service1:latest
```

but something like this will work:

```
services:
    service1:
        build:
            dockerfile: ./docker/Dockerfile
            context: ./service1
```

I would guess, in almost total ignorance, this might have something to do with the containers receiving different names from what is then expected by the supervisor?  But no error message is generated that I can see and the balena push logs just seem to indicate that installation is continuing.

Perhaps this is intended behaviour, if so would be good to document it somewhere.
