### ISSUE TITLE
ssh: CLI incorrectly parsing service names when device is in local mode

### ISSUE THREAD

**Issue by tmigone** [balena-io/balena-cli#2252]
# Expected Behavior

In local mode, when running `balena ssh [device_ip][service]` with a `service` name which does not exist, the suggested list of available services should match the `docker-compose` service names.

For example, for this compose file:
```
version: '2'

services:

  buster:
    image: balenalib/raspberrypi4-64-debian:buster
    command: balena-idle

  pi-buster:
    image: balenalib/raspberry-pi-debian:buster
    command: balena-idle

```

the expected output should be:

```
✗ balena ssh 192.168.90.179 thisdoesnotexist
Could not find a service on device with name thisdoesnotexist. Available services:
	buster
	pi-buster
```

# Actual Behavior

The available services listed are being incorrectly parsed and/or displayed with `-` and everything in front of it being removed:

```
✗ balena ssh 192.168.90.179 thisdoesnotexist
Could not find a service on device with name thisdoesnotexist. Available services:
	buster
	buster
```

# Steps to Reproduce the Problem

Described above.

# Specifications

- **balena CLI version:** v12.44.9
- **Cloud backend**: balenaCloud
- **Operating system version:** macOS Catalina 10.15.7
- **32/64 bit OS and processor:** 64-bit macOS on 64-bit Intel processor
- **Install method:** npm
- **If npm install, Node.js and npm version:** node v12.18.3
