### ISSUE TITLE
balena build: we should automatically authenticate to bh.cr

### ISSUE THREAD

**Issue by klutchell** [balena-io/balena-cli#2478]
The workaround to use registry secrets with your balenaCloud username and token as described here:

- https://github.com/balena-io/open-balena-registry-proxy/blob/master/README.md#private-registries
- https://www.balena.io/docs/learn/deploy/deployment/#private-base-images

```yaml
# registry-secrets.yml
'bh.cr':  # balenaHub Container Registry
    username: u_username
    password: session token or api key
```
