### ISSUE TITLE
installable Github Action for balena-cli

### ISSUE THREAD

**Issue by ab77** [balena-io/balena-cli#2572]
A simple one line installation step in the spirit of: https://github.com/actions/setup-node

(e.g.)

```
- name: Setup balena-cli
  uses: balena-io/setup-balena-cli@v1
    with:
      node-version: latest
```
