### ISSUE TITLE
'balena push' produces spammy progress bar output in CI

### ISSUE THREAD

**Issue by jrr** [balena-io/balena-cli#2726]
The animated progress bar is nice in an interactive terminal, but it's really junking up our CI logs. 

<img width="778" alt="github-balena-ci-output" src="https://github.com/balena-io/balena-cli/assets/164652/44dd6a3c-920b-467d-b37c-331d5fef0afa">

(also there seem to be extra newlines in the summary table)

A similar discussion exists in this issue about the unicorn: https://github.com/balena-io/balena-cli/issues/1001

I'm using balena-cli `17.5.1` in GitHub Actions via the [community-cli-action](https://github.com/balena-labs-research/community-cli-action) like this:
```yaml
      - name: balena push
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{ secrets.balena-token }}
          balena_cli_version: 17.5.1
          balena_cli_commands: >
            push ${{ inputs.balena-fleet }} --note CI-${{ github.ref_name }}.${{ github.sha }} --release-tag origin ci-${{ github.ref_name }}
```
